# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.SecondCategoryModel', verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='secondcategorymodel',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.FirstCategoryModel', verbose_name='所属父类'),
        ),
    ]
