# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180529_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsmodel',
            name='assets_sn',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='资产唯一编号'),
        ),
        migrations.AlterField(
            model_name='assetsmodel',
            name='assets_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='assetsmodel',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品牌名称'),
        ),
        migrations.AlterField(
            model_name='assetsmodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='资产名称'),
        ),
        migrations.AlterField(
            model_name='assetsmodel',
            name='nums',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='资产剩余可用'),
        ),
        migrations.AlterField(
            model_name='assetsmodel',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='资产价格'),
        ),
        migrations.AlterField(
            model_name='assetsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('IDLE', '闲置'), ('IN_USE', '在用'), ('SCRAP', '报废'), ('NOT_HAVE', '暂无,需购买')], default='IDLE', max_length=30, null=True, verbose_name='资产状态'),
        ),
        migrations.AlterField(
            model_name='firstcategorymodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='一级分类'),
        ),
        migrations.AlterField(
            model_name='secondcategorymodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='二级分类'),
        ),
        migrations.AlterField(
            model_name='secondcategorymodel',
            name='parent_category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.FirstCategoryModel', verbose_name='所属父类'),
        ),
    ]
