# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180529_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptmodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='住址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.DeptModel', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personal_email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True, verbose_name='个人邮箱'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personal_home',
            field=models.CharField(blank=True, default='无', max_length=100, null=True, verbose_name='个人主页'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True, verbose_name='工作邮箱'),
        ),
    ]
