# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 22:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_userassetmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassetmodel',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.AssetsModel', verbose_name='资产信息'),
        ),
        migrations.AlterField(
            model_name='userassetmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
