# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 09:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180529_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassetmodel',
            name='apply_status',
            field=models.IntegerField(blank=True, choices=[(1, '审核中'), (2, '通过'), (3, '不同意'), (4, '正在配置'), (5, '已完成，正在使用')], default=1, null=True, verbose_name='申请状态'),
        ),
        migrations.AlterField(
            model_name='userassetmodel',
            name='asset',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.AssetsModel', verbose_name='资产信息'),
        ),
        migrations.AlterField(
            model_name='userassetmodel',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
