# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20180530_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassetmodel',
            name='asset_name',
            field=models.CharField(default='', max_length=100, verbose_name='申请资产名称'),
        ),
    ]
