# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_userassetmodel_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassetmodel',
            name='remark',
            field=models.TextField(null=True, verbose_name='备注'),
        ),
    ]
